### ISSUE TITLE
[PE-D][Tester C] Violate `Constraint-Typing-Preferred`

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W13-2/tp#112]
# Problem 

From the module website: 

> The product should be targeting users who can type fast and prefer typing over other means of input.
Reason: to increase comparability of products, and to make feature evaluation easier for peer evaluators.

Did not document how to toggle between tabs using commands nor was it mentioned in the UG.

# Solution 

Document it in the UG or implement a command to toggle between tabs. For example, `gt` for Vim.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Zxun2/ped#6

**Comment by Tempura-Person** [comment]
Include shortcut keys Ctrl+1, Ctrl+2, Ctrl+3 in UG
