### ISSUE TITLE
[PE-D][Tester C] `Group` is an unknown command

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W13-2/tp#126]
# Problem 

The command `group m/add g/Team Dynamite` is specified under command summary and heavily mentioned in the developer guide.

![image.png](https://raw.githubusercontent.com/Zxun2/ped/main/files/81aa02d6-859e-4a51-a6ab-6d98f089c4f3.png)

# Solution 

Probably something to do with the parser.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Zxun2/ped#11

**Comment by Tempura-Person** [comment]
remove group from UG/DG
